version: "1.0"
stages:
  - "clone"
  - "prepare"
  - "plan"
  - "apply"
  - "deploy"
steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "Mansipande28/Mod3"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  SetupAuth:
    image: alpine:3.9
    title: Setting up aws auth
    stage: prepare
    commands:
      - cf_export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - cf_export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  plan:
    title: Terraform Plan
    type: freestyle
    working_directory: './Mod3'
    arguments:
      image: 'hashicorp/terraform'
      commands:
        - terraform init
        - terraform validate
        - terraform plan
    stage: plan

  deploy:
    title: Terraform Apply
    type: freestyle
    working_directory: './Mod3'
    arguments:
      image: 'hashicorp/terraform'
      commands:
        - terraform init
        - terraform apply -auto-approve
    stage: "deploy"

